services:
  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file: .env
    depends_on:
      - db

  backend:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./public:/app/public:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  db:
    image: mariadb
    ports:
      - "3310:3306"
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/mysql"
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"

volumes:
  db_data:
    driver: local
